name: "eval() is GOOD"
on:
  issue_comment:
    types: created
jobs:
  boing:
    name: "knock knock"
    if: ${{ github.event.sender.login == 'pradep khosla' || github.event.sender.login == 'SheepTester' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: echo '${{ github.event.comment.body }}'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
